site_name: Mesh for Data
site_description: A cloud-native platform to control data usage
copyright: Made with ❤️ by Mesh for Data contributors.
repo_name: ibm/the-mesh-for-data
repo_url: https://github.com/ibm/the-mesh-for-data
edit_uri: edit/master/website/docs/

nav:
- About: index.md
- Get Started:
  - get-started/quickstart-v2.md
  - samples/notebook-v2.md
- Concepts:
  - concepts/introduction.md
  - concepts/architecture.md
  - Plugins:
    - concepts/connectors.md
    - concepts/modules.md
  - Reference:
    - reference/crds.md
    - Connectors: reference/connectors.md
- Contribute:
  - About: contribute/index.md
  - contribute/environment.md
  - contribute/build-test.md
  - contribute/flow.md
  - Documentation:
    - contribute/documentation/index.md
    - contribute/documentation/formatting.md
    - contribute/documentation/style.md
  - Plugins:
    - contribute/modules.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ibm/the-mesh-for-data

theme:
  name: material
  language: en
  custom_dir: overrides
  include_search_page: false
  search_index_only: true
  palette:
    primary: light blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
  favicon: img/logo.svg # this icon appears in the browser's tab
  logo: img/logo.svg # this icon appears in the top left corner on each page
    
markdown_extensions:
  - toc:
      permalink: false
  - footnotes
  - admonition
  - codehilite
  - meta
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  # disable temporarely because its freezing the page
  - search:
      prebuild_index: python
      lang:
      - en

extra_css:
    - assets/stylesheets/custom.css
    - assets/stylesheets/version-select.css

extra_javascript:
    - assets/javascripts/version-select.js
