# Copyright 2021 IBM Corp.
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: katalog-connector
  namespace: m4d-system
  labels:
    app: katalog-connector
spec:
  selector:
    matchLabels:
      app: katalog-connector
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: katalog-connector
        m4d.ibm.com/componentType: connector
    spec:
      serviceAccountName: katalog-connector
      containers:
      - name: katalog-connector
        image: katalog-connector:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: katalog-connector
spec:
  selector:
    app: katalog-connector
  ports:
  - port: 8080
    targetPort: http
