# Copyright 2021 IBM Corp.
# SPDX-License-Identifier: Apache-2.0
---
# ClusterRole katalog-editor allows users to manage assets.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katalog-editor
rules:
- apiGroups: ["katalog.m4d.ibm.com"]
  resources: ["assets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["secret"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
# ClusterRole katalog-viewer allows viewing assets.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katalog-viewer
rules:
- apiGroups: ["katalog.m4d.ibm.com"]
  resources: ["assets"]
  verbs: ["get", "list", "watch"]
---
# Grant katalog-connector service the katalog-editor Role.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: katalog-connector-editor
roleRef:
  kind: ClusterRole
  name: katalog-editor
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: katalog-connector
  namespace: m4d-system
