name: Release
on: create
jobs:
  update-release-branch:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/heads/releases/') }}
    steps:
    - id: version
      name: Infer version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/heads/releases/}
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install yq
      run: make ./hack/tools/bin/yq
    - run: RELEASE=${{ steps.version.outputs.version }} ./hack/release.sh
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
    - name: 'Create new tag'
      if: success()
      uses: actions/github-script@v4.0.2
      with:
        github-token: ${{ secrets.TAG_PSAT }}
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/v${{ steps.version.outputs.version }}",
            sha: context.sha
          })
